compass:
  name: "&c&lТрекер"
  lore:
    - "&7Указывает на ближайшого терминатора"
  update-interval: 40

sounds:
  enabled: true
  terminator-killed: "ENTITY_ENDER_DRAGON_GROWL"
  all-killed: "UI_TOAST_CHALLENGE_COMPLETE"
