compass:
  name: "<!italic><red><bold>Трекер</bold></red>"
  lore:
    - "<!italic><gray>Указывает на ближайшого терминатора</gray>"
  update-interval: 40

sounds:
  enabled: true
  terminator-killed: "entity.ender_dragon.growl"
  all-killed: "ui.toast.challenge_complete"
